# Generated by Django 3.0.3 on 2020-04-15 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('author', models.CharField(max_length=16, verbose_name='Author')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Published')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=5, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visterName', models.CharField(max_length=16, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('content', models.CharField(max_length=240, verbose_name='Comment')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Published')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogs.Article', verbose_name='博客')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogs.Tags'),
        ),
    ]
